apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-deployment
spec:
  # nodeSelecter: field that you can specify what worker nodes you want the pods to run on
  selector:
    matchLabels:
      app: nginxdeployment
  template:
    metadata:
      labels:
        app: nginxdeployment
    spec:
      containers:
        - name: nginxdeployment
          image: nginx:latest
          ports:
            - containerPort: 80
